FROM tensorflow/tensorflow:latest-devel-gpu-py3

# add mount directory
# ADD . /develop/ChineseCalligraphyGenerationModel
# ADD ../experiments/data /data

RUN pip install imageio


# run bash
RUN /bin/bash